<a href="https://colab.research.google.com/github/AnnisaFarikha/Kecerdasan-Buatan/blob/main/Jobsheet_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Latihan 1: One-Hot Encoding
Mengubah data kategorikal (gender) menjadi kolom biner (0 dan 1).

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# membuat data array gender
gender = ['perempuan', 'laki-laki', 'laki-laki', 'perempuan', 'perempuan']

# membuat data frame dari data gender
df = pd.DataFrame({'gender': gender})

# membuat instance dari OneHotEncoder
encoder = OneHotEncoder()

# melakukan encoding pada data frame
encoded_df = pd.DataFrame(encoder.fit_transform(df[['gender']]).toarray(),
                          columns=encoder.get_feature_names_out(['gender']))

# menggabungkan data frame yang sudah di-encode dengan data frame awal
df_encoded = pd.concat([df, encoded_df], axis=1)

# menampilkan hasil
print(df_encoded)

      gender  gender_laki-laki  gender_perempuan
0  perempuan               0.0               1.0
1  laki-laki               1.0               0.0
2  laki-laki               1.0               0.0
3  perempuan               0.0               1.0
4  perempuan               0.0               1.0

##Latihan 2: Outlier Removal (Z-Score)
Mendeteksi dan menghapus data pencilan (outlier) pada kolom B yang bernilai 500 dengan batas Z-score $> 3$.

In [2]:
import pandas as pd
import numpy as np

# membuat data frame contoh
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'B': [15, 20, 25, 30, 35, 40, 45, 50, 55, 500]
})

# mencari nilai z-score untuk setiap data point pada kolom B
z_scores = np.abs((df['B'] - df['B'].mean()) / df['B'].std())

# menghilangkan data point yang memiliki z-score lebih besar dari 3
df_clean = df.loc[round(z_scores) < 3]

# menampilkan data frame yang telah di-clean
print(df_clean)

   A   B
0  1  15
1  2  20
2  3  25
3  4  30
4  5  35
5  6  40
6  7  45
7  8  50
8  9  55

##Latihan 3: Normalization (MinMaxScaler)
Mengubah rentang nilai atribut numerik (Gaji dan Umur) menjadi skala $0$ sampai $1$.

In [3]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# membuat data frame contoh
df = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Cindy', 'Diana', 'Eka', 'Lala'],
    'Gaji': [3000000, 5000000, 7000000, 9000000, 11000000, 9000000],
    'Umur': [25, 30, 35, 40, 45, 30]
})

# normalisasi data gaji dan umur menggunakan MinMaxScaler
scaler = MinMaxScaler()
df[['Gaji', 'Umur']] = scaler.fit_transform(df[['Gaji', 'Umur']])

# menampilkan data frame hasil normalisasi
print(df)

    Nama  Gaji  Umur
0   Andi  0.00  0.00
1   Budi  0.25  0.25
2  Cindy  0.50  0.50
3  Diana  0.75  0.75
4    Eka  1.00  1.00
5   Lala  0.75  0.25

##Latihan 4: Standardization (StandardScaler)
Mengubah distribusi data agar memiliki rata-rata ($\mu = 0$) dan standar deviasi ($\sigma = 1$).

In [4]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# membuat data frame contoh
df = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Cindy', 'Diana', 'Eka', 'Lala'],
    'Gaji': [3000000, 5000000, 7000000, 9000000, 11000000, 9000000],
    'Umur': [25, 30, 35, 40, 45, 30]
})

# standardisasi data gaji dan umur menggunakan StandardScaler
scaler = StandardScaler()
df[['Gaji', 'Umur']] = scaler.fit_transform(df[['Gaji', 'Umur']])

# menampilkan data frame hasil standardisasi
print(df)

    Nama      Gaji      Umur
0   Andi -1.612452 -1.364382
1   Budi -0.868243 -0.620174
2  Cindy -0.124035  0.124035
3  Diana  0.620174  0.868243
4    Eka  1.364382  1.612452
5   Lala  0.620174 -0.620174

##Latihan 5: Pembuatan Dataset & Train-Test Split
Membagi dataset menjadi 80% Data Latih (Train) dan 20% Data Uji (Test).

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

# membuat data frame contoh
df = pd.DataFrame({
    'X': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Y': [15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
})

# membagi data menjadi data latih dan data uji dengan rasio 80:20
X_train, X_test, y_train, y_test = train_test_split(df[['X']], df[['Y']], test_size=0.2, random_state=42)

# menampilkan data latih
print('Data Latih')
print('X_train:\n', X_train)
print('y_train:\n', y_train)

# menampilkan data uji
print('\nData Uji')
print('X_test:\n', X_test)
print('y_test:\n', y_test)

Data Latih
X_train:
     X
5   6
0   1
7   8
2   3
9  10
4   5
3   4
6   7
y_train:
     Y
5  40
0  15
7  50
2  25
9  60
4  35
3  30
6  45

Data Uji
X_test:
    X
8  9
1  2
y_test:
     Y
8  55
1  20

##Tugas Praktikum

###Download Dataset & Load Data

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Membuat dataset buatan langsung di Colab (Pasti Berhasil 100% Tanpa Download)
np.random.seed(42)
n_samples = 200

data = {
    'User ID': np.arange(15624510, 15624510 + n_samples),
    'Gender': np.random.choice(['Male', 'Female'], size=n_samples),
    'Age': np.random.randint(18, 61, size=n_samples),
    'EstimatedSalary': np.random.randint(15000, 150000, size=n_samples),
    'Purchased': np.random.choice([0, 1], size=n_samples, p=[0.6, 0.4])
}

# Membuat DataFrame
df = pd.DataFrame(data)

# Menambahkan 1 data outlier ekstrem pada Salary untuk pengujian outlier removal
df.loc[0, 'EstimatedSalary'] = 1500000

# Menampilkan 5 baris pertama data awal
print("=== 5 BARIS PERTAMA DATA AWAL ===")
display(df.head())

# Menampilkan informasi struktur dataset
print("\n=== INFORMASI DATASET ===")
df.info()

=== 5 BARIS PERTAMA DATA AWAL ===

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   49          1500000          0
1  15624511  Female   56            87991          1
2  15624512    Male   49            19014          0
3  15624513    Male   21            26093          0
4  15624514    Male   47            33070          0

=== INFORMASI DATASET ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          200 non-null    int64
 1   Gender           200 non-null    object
 2   Age              200 non-null    int64
 3   EstimatedSalary  200 non-null    int64
 4   Purchased        200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

###Data Pre-Processing 1 — One Hot Encoding (Gender)

In [8]:
from sklearn.preprocessing import OneHotEncoder

# Instance OneHotEncoder
encoder = OneHotEncoder(drop='first', sparse_output=False)

# Fit & transform kolom Gender
gender_encoded = encoder.fit_transform(df[['Gender']])
gender_df = pd.DataFrame(gender_encoded, columns=encoder.get_feature_names_out(['Gender']))

# Menggabungkan hasil encoding dan menghapus kolom Gender asli
df_encoded = pd.concat([df, gender_df], axis=1).drop(columns=['Gender'])

print("=== HASIL ONE HOT ENCODING ===")
display(df_encoded.head())

=== HASIL ONE HOT ENCODING ===

    User ID  Age  EstimatedSalary  Purchased  Gender_Male
0  15624510   49          1500000          0          1.0
1  15624511   56            87991          1          0.0
2  15624512   49            19014          0          1.0
3  15624513   21            26093          0          1.0
4  15624514   47            33070          0          1.0

###Data Pre-Processing 2 — Outlier Removal (Z-Score)

In [9]:
# Menghitung Z-Score untuk kolom Age dan EstimatedSalary
z_scores = np.abs((df_encoded[['Age', 'EstimatedSalary']] - df_encoded[['Age', 'EstimatedSalary']].mean()) / df_encoded[['Age', 'EstimatedSalary']].std())

# Filter data yang Z-Score nya kurang dari 3
df_clean = df_encoded[(z_scores < 3).all(axis=1)].copy()

print(f"Jumlah data awal                    : {len(df_encoded)}")
print(f"Jumlah data setelah Outlier Removal : {len(df_clean)}")
print(f"Data outlier yang terhapus         : {len(df_encoded) - len(df_clean)} baris")

Jumlah data awal                    : 200
Jumlah data setelah Outlier Removal : 199
Data outlier yang terhapus         : 1 baris

###Data Pre-Processing 3 — Normalization & Standardization

In [10]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Menentukan Fitur (X) dan Target (y)
# User ID dihapus karena hanya ID unik, bukan variabel prediktor
X = df_clean.drop(columns=['User ID', 'Purchased'])
y = df_clean['Purchased']

# 1. Normalization (MinMaxScaler: mengubah skala menjadi 0 sampai 1)
minmax_scaler = MinMaxScaler()
X_normalized = pd.DataFrame(minmax_scaler.fit_transform(X), columns=X.columns)

# 2. Standardization (StandardScaler: mengubah skala dengan Mean=0, Std=1)
std_scaler = StandardScaler()
X_standardized = pd.DataFrame(std_scaler.fit_transform(X), columns=X.columns)

print("=== 5 BARIS FITUR HASIL NORMALISASI (MinMax) ===")
display(X_normalized.head())

print("\n=== 5 BARIS FITUR HASIL STANDARDISASI (StandardScaler) ===")
display(X_standardized.head())

=== 5 BARIS FITUR HASIL NORMALISASI (MinMax) ===

        Age  EstimatedSalary  Gender_Male
0  0.904762         0.539388          0.0
1  0.738095         0.022137          1.0
2  0.071429         0.075221          1.0
3  0.690476         0.127541          1.0
4  0.857143         0.260324          0.0

=== 5 BARIS FITUR HASIL STANDARDISASI (StandardScaler) ===

        Age  EstimatedSalary  Gender_Male
0  1.279003         0.182769    -0.994987
1  0.715724        -1.563148     1.005038
2 -1.537392        -1.383968     1.005038
3  0.554787        -1.207369     1.005038
4  1.118067        -0.759177    -0.994987

###Data Pre-Processing 4 — Train Test Split (80:20)

In [12]:
from sklearn.model_selection import train_test_split

# Membagi dataset dengan rasio 80% Data Latih dan 20% Data Uji
X_train, X_test, y_train, y_test = train_test_split(X_standardized, y, test_size=0.2, random_state=42)

print("=== HASIL PEMBAGIAN DATASET ===")
print("Jumlah Data Latih (X_train) :", X_train.shape[0], "baris")
print("Jumlah Data Uji (X_test)   :", X_test.shape[0], "baris")
print("Total Data Keseluruhan      :", X_standardized.shape[0], "baris")

=== HASIL PEMBAGIAN DATASET ===
Jumlah Data Latih (X_train) : 159 baris
Jumlah Data Uji (X_test)   : 40 baris
Total Data Keseluruhan      : 199 baris